playframework/playframework.com

README.md
app/utils/GitFileRepository.scala

`Git.fetch()....setRemoveDeletedRefs(true)...call()` doesn't produce a stable result. When it is called, if the remote master branch is in the local ref then it is deleted from the refs. If it is absent from the local refs then it is added to them. This means that the master appears only every second fetch. This means our 2.4.x docs only appear half the time.
The "fix" is to perform another fetch without the `setRemoveDeletedRefs(true)` flag set. :)

Fix bug with master docs showing up intermittently

---

app/controllers/Application.scala
app/models/Releases.scala
app/views/download.scala.html
app/views/index.scala.html

Modified the index page and the downloads page. One consequence of this is that we no longer get the most recent Play version from Activator, which I don't think ever made sense anyway.
See screenshots:

Added ability to name releases

---

app/controllers/Application.scala
app/controllers/documentation/DocumentationController.scala
app/views/documentation/nav.scala.html
conf/routes

Once change the documentation lang, from next time I wanna see changed language documentation again.
(jp latest documentation is still Play2.2, so when click header documentation link, redirect to jp Play2.2 doc anytime)
- `POST /preferred/:lang` is not used(is this true?), so just change a little bit.
- set change lang in cookie based on messageApi interface
- from next time access, if there is no lang info in path, cookie lang is prefer than accept language.
- not to use `GET /preferred/:lang` as open redirector, validate the path parameter is nor external url.

set changed lang in cookie

---

app/assets/javascripts/main.js
app/views/download.scala.html

Previously we tried to detect when Google Analytics was blocked and ran alternative logic. But it turns out to be hard to detect when it's blocked. Detecting presence of the _gaq array can't be relied on, since users are encouraged to create that array if needed (we create the array in two places). Detecting other objects is unreliable since they may not have loaded yet or they may have been replaced by a shim (Ghostery does this).
Instead we take the dumb-but-effective approach of trying to use Google Analytics for up to 3 seconds, but then manually starting the download if we need to. This has the added benefit of handling issues with Google Analytics being slow.
In some cases, i.e. when ads are blocked, this will delay the download from starting. We now show the "Getting started" …

Make downloads work when Google Analytics is blocked

---

app/models/Releases.scala
app/views/download.scala.html

Change downloads to use https instead of http. This is probably a better default anyway.

Fix mixed content error for downloads

---

app/assets/css/modules/_page.styl

This adds CSS styling for the `section-marker` class which is used to create an anchor icon for each headline in the documentation.
The corresponding PR in [play-doc](https://github.com/playframework/play-doc) is [#17](https://github.com/playframework/play-doc/pull/17).

Styling for anchor icon

---

app/controllers/Application.scala

I found that the Play Framework website allows redirecting to any URL through the trailing slash removal code. This is not a serious security issue because currently there's no members section on the website where the user could enter credentials and generally the audience is well-educated, still it allows phishing attacks by an attacker website appearing trustworthy since the domain name in the link sent to the target user is the trusted playframework.com. That's why it's probably better to fix than to leave it open.
**Proof of concept:**
* [https://playframework.com////evilzone.org/](https://playframework.com////evilzone.org/)
* [https://playframework.com////evilzone.org/hacking-and-security/](https://playframework.com////evilzone.org/hacking-and-security/)
* …

Fix open redirect vulnerability in trailing slash removal

---

app/assets/css/main.styl
app/assets/css/pages/_documentation.styl
app/views/main.scala.html

On small displays, the banner will obscure the documentation, so add a media query to hide it when the display is small enough.
Also hide the menu "aside" block when on mobile devices, as it's pretty huge.  Technically should be below or a "side swipe" but I lack the expertise to do that.

Responsive design fixes

---

app/actors/ActivatorReleaseActor.scala
app/assets/javascripts/main.js
app/views/commonSidebar.scala.html
app/views/documentation/v2.scala.html
conf/application.conf
public/markdown/community-process.md
public/markdown/contributing.md

Changed links to point to lightbend.com and text to point to Lightbend where appropriate.
There are some pages I'm not too sure about, such as the historical Outreachy pages and the play 1.0 links which I have not changed.

Update pages to use Lightbend instead of Typesafe

---

app/assets/css/pages/_download.styl
app/assets/javascripts/main.js
app/controllers/Application.scala
app/controllers/documentation/DocumentationController.scala
app/controllers/documentation/Router.scala
app/models/PlayExampleProjects.scala
app/views/download.scala.html
conf/application.conf
conf/playExamples.json
project/plugins.sbt

Adds an example projects section to the Play download page at the top of the download page:
/cc @corruptmemory
Once we've updated the API to allow us to fetch the sample project names, we should be able to use that for metadata instead of the hard-coded JSON.

Add example projects to Play downloads page

---

app/assets/css/modules/_page.styl
app/assets/css/pages/_home.styl
app/views/index.scala.html

This removes the annoying black bar when viewing the download page on a narrow screen, and also makes sure the buttons on the home page are centered and show up. These buttons are hidden for screens below 700px since links to the same content appear elsewhere on the page.

Make sure home and download pages look good on smaller screens

---

app/controllers/Application.scala
app/models/PlayExampleProjects.scala
app/views/download.scala.html
app/views/seedDownload.scala.html
app/views/starterDownload.scala.html

This is just a temporary fix to exclude examples that have parameters. Eventually we should create a form for downloading the project.

Fix issue with template params

---

app/assets/css/pages/_download.styl
app/controllers/Application.scala
app/models/PlayExampleProjects.scala
app/views/download.scala.html
app/views/seedDownload.scala.html

The HTML for the seed projects is now generated from the example code service. It shows both the `sbt new` command and a form to download.

Allow downloading of seeds directly from site

---

app/views/index.scala.html

We've changed domain...
https://www.theguardian.com/info/developer-blog/2014/feb/18/how-the-guardian-successfully-moved-domain
...and shifted to HTTPS-only!
https://www.theguardian.com/info/developer-blog/2016/nov/29/the-guardian-has-moved-to-https

Update link to the Guardian using current domain and scheme

---

app/views/outreachy/round15.scala.html

We were linking to the old urls for outreachy.

Fix outreachy site

---

app/assets/css/pages/_download.styl
app/views/download.scala.html

added instruction link to each alternative download version headings from 2.3 upwards

Issue #61 fix by adding an instruction link

---

app/views/vulnerabilities.scala.html

security@playframework.org still works, but it should be playframework.com.

Changed security email address to playframework.com

---

app/controllers/Application.scala
app/views/gettingStarted.scala.html

@dwijnand, @ignasi35, The objective of this is to change the recommended example (Follow the Hello World Tutorial)  on the https://www.playframework.com/getting-started page to point to the correct Hello World Tutorial examples. In addition, I made some edits to simplify and clarify the page.  
The changes I made look good when I build the web pages except, they do not display the links to download the Hello World Tutorials from Tech Hub:
No links appear here.
Maybe it needs to be live to pull in the links from the example-code-service? If not, could you take a look at the Application controller, I might have made a mistake while switching out the starters examples for tutorials. For your reference, on Tech Hub, the play-templates.conf file defines them like this:
```hocon
tutorials = [
{ …
```

WIP change Try play page example from starter project to tutorials

---

app/views/main.scala.html

Google+ is being shutdown:
https://support.google.com/plus/answer/9195133?hl=en-GB&authuser=0
This removes all links to it.

Remove Google+

---

app/controllers/documentation/DocumentationController.scala

Related to
- https://github.com/playframework/playframework/issues/8609
- https://github.com/playframework/playframework.com/issues/252
I changed the behavior of "showing old Japanese documents when accessing the latest document" and changed to "show English documents if there is no corresponding Japanese document for the latest version".
There used to be a project to translate documents into Japanese, but unfortunately that project has already become inactive. The latest version of the Japanese document is 2.4.
playframework.com gives preference to language over version when accessing the latest documentation. As a result, Japanese users are always shown outdated documents, and I have seen people who are in trouble by referring to information that is already incorrect. I have told many …

Show translated documentation only when the latest version is translated

---

.gitignore
app/assets/css/pages/_documentation.styl

When opening via phone or tablets, some contents overflowed.
But it looks bad, and should wrap or be scrollable.
Related to https://github.com/playframework/playframework.com/issues/180.
I think [this link](https://www.playframework.com/documentation/2.6.x/Migration26) is most ugly, and took some screenshots for example.

Fix broken styles.

---

.gitignore
app/assets/css/modules/_typography.styl

some text for `<code>` is overlaid and un-readable for mobile.
Fixed it :smile:

fix unreadable texts for mobile

---

app/assets/css/modules/_oneTrust.styl
app/views/cookie.scala.html
app/views/main.scala.html

@ignasi35 @ennru 
This updates the Play Framework website to the latest cookie banner code. It uses geo-location to present Californian users with CCPA specific language in the preference center, cookie banner and footer link. The rest the world see's existing GDPR messaging. 
Also the preference center and cookie banner has a new look and feel as part of this upgrade, that all visitors will now see.
Example of the Preference center newer look:

ccpa cookie banner upgrade

---

app/controllers/Application.scala
app/controllers/Blog.scala
app/views/blog/graal.scala.html
app/views/blog/index.scala.html
app/views/blog/socketio.scala.html
app/views/main.scala.html
build.sbt
conf/routes
project/plugins.sbt

Migrate two relevant blog posts into static content.
Redirect non-RC and non-milestone releases url to corresponding tag on github.
Keep the blog menu item and link to minimal blog index page
---
The content was converted via https://markdowntohtml.com/ 🤷‍♂️

Migrate blog

---

app/views/documentation/v1.scala.html

It's broken now, and that's a pity as the docs are quite complete!

Fix API search for Play1

---

conf/playReleases.json
public/markdown/changelog.md

Updates the website for release 2.8.11. 
Note, that I removed 2.8.9 and 2.8.10 as I consider them invalid releases, better not to have them in the website to avoid confusion. 
* v2.8.9 had issue with play-ws and scala-java8-compat
* v2.8.10 was build using JDK11 (btw, 2.8.9 as well)
I moved all issues and PRs solved since 2.8.8 to milestone 2.8.11.

Play 2.8.11 release

---

app/views/gettingStarted.scala.html

Fixes #445
- This pull request changes a link to oracle JDK to open JDK on [Getting started page](https://www.playframework.com/getting-started). Issue is explained on playframework/playframework#10938.
- Related pull request was made on playframework/playframework#10982.

Fix docs: change oracle jdk link to open jdk link

---

app/views/sponsors.scala.html

There is no way to contact us in private (you could send a message via opencollective, but not everyone is aware of that or finds the button).
<kbd><img width="600" src="https://user-images.githubusercontent.com/644927/150605392-5fd1e30d-d180-4a3f-899b-3b19d21c2f97.png" /></kbd>

Add e-mail contact for premium sponsors

---

app/views/documentation/v1.scala.html
app/views/documentation/v2.scala.html

It looks like the book links are broken or discontinued by their publishers. This PR simply removes this links to the books in the `aside`.
Feel free to reject this PR if it is not the right thing to do. 
Cheers!

Remove old or broken book links from documentation sidebar.

---

app/assets/css/modules/_header.styl
app/views/commonSidebar.scala.html
app/views/documentation/v2.scala.html
app/views/getInvolved.scala.html
app/views/index.scala.html
app/views/main.scala.html
app/views/modules/list.scala.html
public/markdown/community-process.md
public/markdown/contributing.md

Just replacing links.
There were also places were the old google groups mailing list still was used.
Tested locally.

Switch to GitHub Discussions (+ rm outdated Google Groups)

---

.github/workflows/build-test.yml
README.md

My `clone.defaultRemoteName` is set to `upstream` in my `~/.gitconfig`, so the tests didn't work because they read from the `origin` remote by default....

Make sure remote of the cloned repo is called "origin" + add .gitconfig tip to README

---

app/views/gettingStarted.scala.html

Link to Lightbend sample projects actually pointed to Akka.
This is a bit tough to spot because it's outside of play-doc.  Probably better to move play-doc in its entirety to playframework.com and retire the inline documentation feature -- it never worked very well.

Fix link to point to play-samples

---

conf/messages.bg

The previous value, ‘българин’, means ‘a Bulgarian person’, or ‘a Bulgarian man’. The name of the language should be ‘български’.
This PR also capitalizes the language name. In Bulgarian, the language name is not a proper name and I can be all lowercase, but the same is true for French. Since French is capitalized, as well as English and Turkish (where it's a proper name), it looks visually better if all language names are capitalized (as if they were at the beginning of the sentence). This is how Wikipedia does it, for example.

Fix the name of the Bulgarian language

---

app/models/PlayExampleProjects.scala
app/views/gettingStarted.scala.html
conf/application.conf
conf/playSamples_2.8.x.json
conf/playSamples_2.9.x.json
conf/playSamples_3.0.x.json

It's just used to display/link the "Play Hello World Projects" under "Try the Hello World Tutorial" in https://www.playframework.com/getting-started
The service was down a couple of days ago, which meant _our_ website was giving 500 server errors.
Also we should no longer depend on Lightbend just to display two hello world project we host in our own GitHub organization anyway.
I just scrapped the JSON that is coming in currently from the service and saved it as json files.
We could of course also parse the play-samples repo and create that json files ourselves, e.g. we could add meta data files to the samples repo in each folder we read. However, no priority right now.

Migrate away from example.lightbend.com webservice

---

project/plugins.sbt

* https://github.com/sbt/sbt-stylus/releases/tag/2.0.0
* https://github.com/sbt/sbt-digest/releases/tag/2.0.0
* https://github.com/sbt/sbt-gzip/releases/tag/2.0.0
They all uses latest sbt-web 1.5 / sbt-js-engine 1.3.x now, but most importantly are now hosted on maven central intead of deprecated https://repo.scala-sbt.org/ (see https://github.com/sbt/sbt/issues/7202)
Tested locally and the assets from this project are generated 1:1 like before.

Upgrade sbt-web plugins

---

app/views/documentation/header.scala.html
app/views/main.scala.html

Current search was using DocSearch v2, which is legacy and looks like was self hosted by Lightbend (?)
v2 is legacy and not supported anymore.
DocSearch v3 needs some changes and is hosted by Aloglia for free now, unfortunately I do not have access to old docsearch config...
Need to implement faceting different than in v2 now (used to filter search results based on version like 2.8.x, 2.9.x 3.0.x, etc.)
- https://www.algolia.com/doc/guides/managing-results/refine-results/faceting/?client=javascript
- https://docsearch.algolia.com/docs/record-extractor/#indexing-content-for-faceting
- https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags
Testing things locally for a bit just in case you are wondering what I am doing.

Add Algolia docsearch metadata

---

app/assets/css/pages/_all-releases.styl
app/views/allreleases.scala.html

This way all releases (2.0.0, 2.0.x,.... ,2.9.0, 2.9.1, ..., 2.9.x) will be crawled automatically. Also this has the advantage that when we cut a new release it will automatically be crawled without configuring anything in the Algolia crawler.
So we can make this page the entry point for crawling the docs and we should be good.
The links will be hidden.

(Hidden) link to each doc 'Home' page from all releases page

---

app/views/documentation/algolia.scala.html

I had to setup a new Algolia account with a new index with new configuration because no one was able to restore the current acount/settings. There were much more problems to solve... Actually even if we could restore the current account we would have to upgrade it to latest Algolia docsearch v3 (was v1). So I had to set up a new Docsearch index with the new crawler v3. In the UI we keep using docsearch v1 because fortunately it's still compatible with index/crawler v3. I didn't know that so I first tried to replace the UI library with the new docsearch v3 UI, however this was a pain because it does only work correctly within a modal but not with our current doc page style with a dropdown... So I was spending way too many hours with bs before I chatted with the Algolia people in their …

Switch to new Algolia search index

---

app/views/documentation/v2.scala.html

Do **not** show when the Algolia crawler visits.
<kbd><img width="670" src="https://github.com/playframework/playframework.com/assets/644927/0bfc4ebb-8aea-4492-8af0-2e089a43f4e2" /></kbd>
See
- https://github.com/playframework/playframework.com/issues/562
- https://support.algolia.com/hc/en-us/articles/17223760387857-What-is-the-user-agent-of-the-Crawler
Tested locally with curl by changing the `User-Agent` header.

Do not display version info on doc pages

---

app/actors/DocumentationActor.scala
app/controllers/documentation/DocumentationController.scala

```
[warn] -- Warning: /home/runner/work/playframework.com/playframework.com/app/actors/DocumentationActor.scala:564:17 
[warn] 564 |            .map(DocumentationSitemap)
[warn]     |                 ^^^^^^^^^^^^^^^^^^^^
[warn]     |The method `apply` is inserted. The auto insertion will be deprecated, please write `actors.DocumentationActor.DocumentationSitemap.apply` explicitly.
[warn] -- Warning: /home/runner/work/playframework.com/playframework.com/app/controllers/documentation/DocumentationController.scala:2[64](https://github.com/playframework/playframework.com/actions/runs/16085402790/job/45395893285#step:12:65):13 
[warn] 264 |    (actor ? GetSummary).mapTo[DocumentationSummary].map { summary =>
[warn]     |             ^^^^^^^^^^
[warn]     |The method `apply` is inserted. The …
```

fix `auto insertion` warnings
