conf/playReleases.json
public/markdown/changelog.md

Add changelog for 2.4.0 release

Add 2.4.0 changelog

---

app/views/download.scala.html

Fixes playframework/playframework#4628

Recomends JDK8 or newer

---

app/assets/css/modules/_typography.styl

Make it easier to see hyperlinks in <code>

---

app/views/getInvolved.scala.html

Number of the commiters:
```
git shortlog -sn --all
```
Number of bug reporters:
I modified [this script](https://gist.github.com/unbracketed/3380407) to export all issues and let Excel do some magic :smile:

Updated community statistics

---

.travis.yml
build.sbt
project/build.properties

Speed up the build and move to container based infrastructure.

Add ivy cache to travis.yml

---

app/assets/css/pages/_documentation.styl
app/models/documentation/Documentation.scala
app/views/documentation/Helpers.scala
app/views/documentation/v2.scala.html
app/views/documentation/versionInfo.scala.html
conf/messages

Add a header that tells you what documentation you're looking at.

Add a version header

---

app/assets/css/pages/_documentation.styl

Fix for https://github.com/playframework/playframework.com/issues/3

Add table CSS

---

app/views/getInvolved.scala.html

Fixes https://github.com/playframework/playframework/issues/5319

Update get-involved to include gitter.im

---

app/assets/css/pages/_algolia.styl
app/assets/css/pages/_index.styl
app/views/documentation/algolia.scala.html
app/views/documentation/header.scala.html
app/views/documentation/v2.scala.html
app/views/main.scala.html

Fixes https://github.com/playframework/playframework.com/issues/62
JS and CSS for dynamic doc searching.

Use algolia for doc search

---

app/assets/css/modules/_header.styl
app/assets/css/pages/_documentation.styl
app/views/documentation/v2.scala.html

Move the search box above, make it large, and make it responsive across system.

Move search box to front and center

---

app/views/documentation/v2.scala.html

Add autofocus

---

app/views/main.scala.html

Add support for https://developers.google.com/structured-data/site-name

Add site name structured data

---

app/actors/DocumentationActor.scala
app/assets/css/pages/_documentation.styl
app/controllers/documentation/DocumentationController.scala
app/views/documentation/v2.scala.html
build.sbt

Adds breadcrumbs to the header.

Add breadcrumbs

---

app/assets/css/modules/_clipboard.styl
app/assets/css/modules/_index.styl
app/views/clipboard.scala.html
app/views/prettify.scala.html
build.sbt

Adds a copy button to copy/paste code segments.

Add clipboard functionality

---

conf/application.conf

This way it skips a step, making it 1 click to edit rather than 2.
The playframework.com version of https://github.com/lagom/lagom/pull/179

Change the gitHubSource URL to edit

---

app/controllers/Modules.scala

[#109] fix(module): send notFound result on dependencies.yml request if module doesn't exist

---

app/views/download.scala.html
app/views/exampleArticle.scala.html

Describe the role of sample projects vs the giter8 seeds when it comes to OOTB security setup.

Add better description of security

---

app/views/commonSidebar.scala.html
app/views/getInvolved.scala.html
app/views/index.scala.html

Fixes https://github.com/playframework/playframework.com/issues/113

Better community involvement links

---

app/views/download.scala.html
app/views/exampleDownload.scala.html
app/views/seedDownload.scala.html
app/views/starterDownload.scala.html

Target the download page to different categories of users and move the starters up to the top.

Change download page verbiage

---

app/views/seedDownload.scala.html
app/views/starterDownload.scala.html

Adds more detail to introduce new people to Play through the starter projects.

Add more handholding to starter projects.

---

app/assets/css/pages/_documentation.styl

Fixes #123
Tested in latest Firefox, Chrome and MS Edge

Fix Dropdown: Enlarge clickable region

---

public/markdown/changelog.md

Corrected latest release version for 2.4 branch to 2.4.10

Updated changelog

---

app/assets/css/pages/_download.styl
app/views/activatorDownload.scala.html
app/views/download.scala.html

Fixes playframework/playframework#5918

Add link to download minimal version of Activator

---

app/views/exampleDownload.scala.html
app/views/starterDownload.scala.html
project/plugins.sbt

I think this will fix the current issue on the website. Will need to figure out why the starter projects aren't found though.

Fix error if starter projects can't be found

---

app/controllers/Application.scala
app/models/PlayExampleProjects.scala
app/views/starterDownload.scala.html
conf/application.conf

Keyword should be "starter" not "seed".
Also added a TTL so projects will be re-fetched for updates every hour.

Properly get starter projects from ECS

---

app/views/index.scala.html

Add Akka HTTP as the underlying engine

---

app/views/main.scala.html

Add blog link

---

public/markdown/changelog.md

Please edit with more details if needed.

Updated changelog with 2.6.2 and 2.5.16

---

app/controllers/Outreachy.scala
app/views/outreachy/round15.scala.html
conf/routes

This mostly updates the round 11 page since we did not get any qualifying applicants for that one.

Add information for outreachy round 15

---

public/markdown/changelog.md

fix 2.6.9 release date

---

app/views/main.scala.html
app/views/support.scala.html

As discussed with team, added a Support tab and page.

Added Support page.

---

app/assets/css/modules/_header.styl

Fixes #195
Note that I haven't tested this locally (just edited in GitHub) so if you want to be cautious you might want to try it out before merging.

Update social icon styles for the new forum URL

---

app/views/seedDownload.scala.html

Fixes https://github.com/playframework/playframework.com/issues/155

Remove outdated security warning on seed template page

---

app/views/seedDownload.scala.html

Scrub scaffold text until https://github.com/playframework/playframework/issues/8270 is resolved

Remove g8 scaffold text from seed template page

---

README.md
conf/playReleases.json
project/build.properties
public/markdown/changelog.md

Info on Play 2.6.15 release, plus some info on how to set up MySQL when running playframework.com locally.

Play 2.6.15 release + MySQL docs

---

.travis.yml
app/actors/Actors.scala
app/controllers/documentation/DocumentationController.scala
app/models/documentation/Config.scala
conf/application.conf
test/controllers/documentation/DocumentationControllerSpec.scala
test/services/github/GitHubSpec.scala

There is a bunch of 404s from our logs which had a bad impact on user experience and also SEO.
This fixes the most important by redirecting to the new/correct pages.

Redirect renamed pages in the docs

---

conf/routes
public/security.txt

Added security.txt

---

conf/playReleases.json
public/markdown/changelog.md

Release Play 2.6.17

---

app/assets/css/main.styl
app/assets/css/pages/_getting-started.styl
app/assets/javascripts/main.js
app/controllers/Application.scala
app/views/allreleases.scala.html
app/views/commonSidebar.scala.html
app/views/gettingStarted.scala.html
conf/application.conf

This is a follow up of #192 by @rstento. There are some changes here that depend on documentation improvements too, so another pull request will be made to improve Play docs and make it consistent
with the changes here.
@rstento, @richdougherty, @gmethvin, and @wsargent, please review.

Improvements for the "try-play" page

---

conf/application.conf

Remove CSP filter configuration

---

public/markdown/contributing.md

Sync with CONTRIBUTING.md in the Play repo.

Update the contributing page

---

app/assets/css/modules/_typography.styl

Improve code CSS style for better readability

---

app/controllers/documentation/DocumentationController.scala
app/utils/HtmlHelpers.scala
test/utils/HtmlHelpersSpec.scala

So that we can have better SEO for these pages.

Better HTML title for documentation pages

---

.gitignore
app/assets/css/pages/_documentation.styl

I fixed it https://github.com/playframework/playframework.com/issues/281.

fix overflow input

---

README.md

remove unnecessary sentence

---

app/views/main.scala.html

related to https://github.com/lagom/lagom.github.io/issues/207

Removes scoop.it

---

conf/application.conf

Fixes https://github.com/playframework/playframework/issues/9908

Adds redirect after content rename

---

.mergify.yml

This relaxes mergify (it was eagerly merging!)

Sync mergify config with play itself

---

conf/playReleases.json
public/markdown/changelog.md

https://github.com/playframework/play-meta/issues/170

Release play 2.8.5

---

app/actors/DocumentationActor.scala
app/controllers/documentation/DocumentationController.scala
app/models/Releases.scala
app/models/github/GitHub.scala
test/services/github/GitHubSpec.scala

add explicit type annotations for implicit val

---

app/controllers/Application.scala
app/controllers/Outreachy.scala
app/models/documentation/Sitemap.scala
app/views/allreleases.scala.html
app/views/code.scala.html
app/views/commonSidebar.scala.html
app/views/getInvolved.scala.html
app/views/index.scala.html
app/views/main.scala.html
app/views/outreachy/round10.scala.html
app/views/outreachy/round15.scala.html
app/views/sponsors.scala.html
build.sbt
project/plugins.sbt
test/utils/GitFileRepositoryPerformanceTest.scala

Upgrading to [2.8.8+](https://github.com/playframework/playframework/releases/tag/2.8.8) needs some tweaking with empty parentheses () in reverse routes, see [#10671](https://github.com/playframework/playframework/pull/10671)

Play 2.8.11 / Scala 2.13.7

---

conf/playReleases.json
public/markdown/changelog.md

Add Play1 v1.7.0 release

---

conf/playReleases.json
project/plugins.sbt
public/markdown/changelog.md

Depends on https://github.com/playframework/play-samples/pull/193

Play 2.8.19

---

app/views/index.scala.html

They handed over the Play project to another company, that company might take over sponsorship as well, we will see 🤞

Remove CiviForm from sponsors

---

conf/playReleases.json

btw, the play website now runs on rc2 with Java 17. yeah.

Add 2.9.0-RC2 as development release

---

app/assets/css/modules/_typography.styl
public/stylesheets/main.css

No (left) padding for code blocks

---

.github/workflows/dependency-graph.yml

Upgrade GitHub action workflows
